### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by ahmedkenawy** [SnorSnor9998/Sunmi-Card-Reader#1]
i got this error while iam trying to add  dependency

> `implementation(files("libs/PayLib-release-1.4.43.aar"))`

but i got this error 
`Null extracted folder for artifact: ResolvedArtifact(componentIdentifier=PayLib-release-1.4.43.aar, variant=local file, variantName=null, artifactFile=C:\Users\User2\AndroidStudioProjects\SunmiPayment\app\libs\PayLib-release-1.4.43.aar, isTestFixturesArtifact=false, extractedFolder=null, publishedLintJar=null, dependencyType=ANDROID, isWrappedModule=false, buildMapping={__current_build__=C:\Users\User2\AndroidStudioProjects\SunmiPayment})
`

**Comment by SnorSnor9998** [comment]
Did you copy the `PayLib-release-1.4.43.aar` to `libs` folder correctly?
Or you try `implementation files('../libs/PayLib-release-1.4.43.aar')`

**Comment by zumrywahid** [comment]
download the current project and run the app first. then copy the libraries correctly.
