### ISSUE TITLE
How to read Card Number and Balance Bank NFC Card?

### ISSUE THREAD

**Issue by yusriltakeuchi** [SnorSnor9998/Sunmi-Card-Reader#2]
I have a bank card money, Flazz (BCA) and Tapcash (BNI). I use the NFC reading method in the Sunmi library, tetapi hasilnya hanya mengembailkan nilai
- uid
- ats
- cardCategory

How to get card information like Card Number, Balance, and more ?
I succeeded in getting it with the IC method, but not with NFC

**Comment by SnorSnor9998** [comment]
I believe those two card you mention are not EMV card instead of Mifare card

**Comment by PedroAbreu21** [comment]
hi, I didn't find documentation for reading mifare tags. Does this repository make this possible?

**Comment by SnorSnor9998** [comment]
@PedroAbreu21 You can check their [documentation](https://developer.sunmi.com/docs/en-US/xeghjk491/fxzeghjk557), there is a doc inside the `.rar` zip file
On `3.4.1.8 Mifare Classic` -> ` 3.4.1.8.1 Verify password of M1 card sector` & `3.4.1.8.2 M1 card read block data`

So far no plan for that.. dont have any mifare card laying around plus each card can be config differently, you can refer on [here](https://kb.supremainc.com/knowledge/doku.php?id=en:1xfaq_how_to_configure_mifare_card_memory_layout)
